### ISSUE TITLE
Detect WebGL

### ISSUE THREAD

**Issue by atorger** [matthiasfeist/nvdb-osm-diff-map#1]
Quite low priority thing, but if your web browser lacks WebGL so it cannot display the vector map, the web page just goes blank and you need to open the javascript console to see what the error is.

**Comment by matthiasfeist** [comment]
Note to self: Implement the following check: https://docs.mapbox.com/mapbox-gl-js/example/check-for-support/

**Comment by matthiasfeist** [comment]
Issue closed since I removed the map
