### ISSUE TITLE
How to load NVDB files from Python

### ISSUE THREAD

**Issue by NKAmapper** [matthiasfeist/nvdb-osm-diff-map#4]
I get "Forbidden" when I try to load the NVDB files with Python, for example for "https://nvdb-osm-map-data.s3.amazonaws.com/osm/Alvesta.osm". Any extra arguments needed for urllib/requests?

**Comment by NKAmapper** [comment]
Ah, got it, just a missing character :)

**Comment by matthiasfeist** [comment]
Haha very nice. Are you starting to import some road?

**Comment by NKAmapper** [comment]
I updated [highway_merge.py](https://github.com/NKAmapper/highway_merge) to load your files automatically after someone asked about it. I have used this script for imports in approx. 100 Norwegian municipalities.

**Comment by matthiasfeist** [comment]
interesting. 
I read through your README file but I am still not really clear about how it works and why it is quicker than the manual import...?
It seems that I still need to go though every way manually, correct tags and connect paths? Or did I misunderstand?

**Comment by matthiasfeist** [comment]
Oh and another thing: This is actually the deprecate project. The new pipline is here: https://github.com/matthiasfeist/nvdb2osm-pipeline
